_wandb:
    value:
        cli_version: 0.26.0
        e:
            3mik4lt73u1p1jp0e72npzd2z77zhcnz:
                codePath: /home/miao/repo/lsy_drone_racing/notebooks/train_level2_ppo.ipynb
                codePathLocal: notebooks/train_level2_ppo.ipynb
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "78151184384"
                        used: "34714431488"
                email: miaoxiaochen0701@gmail.com
                executable: /home/miao/repo/lsy_drone_racing/.pixi/envs/gpu/bin/python
                git:
                    commit: 0f3bf38108aaa874aa3a48ee1117e9f18698d2d6
                    remote: https://github.com/stateirving/lsy_drone_racing.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-d9a59ade-8cf7-026e-f775-bb32b114f71c
                host: Y9000P
                memory:
                    total: "33356804096"
                os: Linux-6.17.0-29-generic-x86_64-with-glibc2.39
                program: /home/miao/repo/lsy_drone_racing/notebooks/train_level2_ppo.ipynb
                python: CPython 3.13.11
                root: /home/miao/repo/lsy_drone_racing
                startedAt: "2026-05-21T18:14:23.327297Z"
                writerId: 3mik4lt73u1p1jp0e72npzd2z77zhcnz
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
            - "2": charts/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": losses/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": reward_components/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": race/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": train/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 2
                - 7
                - 16
                - 41
                - 61
            "4": 3.13.11
            "5": 0.26.0
            "8":
                - 1
            "12": 0.26.0
            "13": linux-x86_64
act_coef:
    value: 0.005
anneal_lr:
    value: true
batch_size:
    value: 8192
clip_coef:
    value: 0.26
clip_vloss:
    value: true
config:
    value: level2.toml
crash_penalty:
    value: 50
cuda:
    value: true
d_act_th_coef:
    value: 0.02
d_act_xy_coef:
    value: 0.05
debug_obs:
    value: false
debug_reward_every:
    value: 0
ent_coef:
    value: 0.02
finish_bonus:
    value: 80
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
gate_axis_coef:
    value: 12
gate_back_bonus:
    value: 4
gate_bonus:
    value: 30
gate_front_bonus:
    value: 4
gate_plane_bonus:
    value: 8
gate_stage_coef:
    value: 5
gate_stage_offset:
    value: 0.35
gate_stage_radius:
    value: 0.24
jax_device:
    value: gpu
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 1.5
minibatch_size:
    value: 1024
missed_gate_penalty:
    value: 8
n_obs:
    value: 2
near_gate_coef:
    value: 0
norm_adv:
    value: true
num_envs:
    value: 256
num_iterations:
    value: 4882
num_minibatches:
    value: 8
num_steps:
    value: 32
obstacle_coef:
    value: 1.5
obstacle_margin:
    value: 0.35
progress_coef:
    value: 10
rpy_coef:
    value: 0.03
seed:
    value: 42
target_kl:
    value: 0.03
time_penalty:
    value: 0.05
torch_deterministic:
    value: true
total_timesteps:
    value: 40000000
update_epochs:
    value: 5
vf_coef:
    value: 0.7
wandb_entity:
    value: null
wandb_project_name:
    value: ADR-PPO-Racing
wrong_side_penalty:
    value: 6
